Feat/mesto update
olgushe4ka/mesto-project pull request #2
Opened 2022-07-31 13:46 UTC by olgushe4ka

2022-08-01 11:06 UTC, antonmishchenkov commented on src/scripts/components/api.js
> +  checkResponse(res) {
**Отлично:**

Отлично, что обработка ответа от сервера вынесена в отдельный метод

2022-08-01 11:10 UTC, antonmishchenkov commented on src/scripts/components/card.js
> +      this._buttonLike.classList.remove("photo-grid__heart_black");
**Надо исправить:**

Любую DOM логику следует осуществлять только после успешного ответа от сервера на соответствующий api запрос.

Следовательно DOM установку/удаление лайка карточке необходимо вынести в отдельный публичный метод класса Card и вызывать его в блоке `then` для `this._removeLike` и `this._addLike` в файле `index.js`

2022-08-01 11:11 UTC, antonmishchenkov commented on src/scripts/components/FormValidator.js
> +    const inputList = Array.from(
**Надо исправить:**

Список полей формы и кнопку сабмита необходимо вынести в конструктор класса в качестве полей, чтобы не искать элементы внутри метода и не передавать их в другие методы. 
Необходимо для того, чтобы доступ к этим статичным элементам формы был во всем классе.

```
this._inputList = ...
this._submitButton = ... 
```

2022-08-01 11:12 UTC, antonmishchenkov commented on src/scripts/components/FormValidator.js
> +    this._formList.forEach((formElement) => {
**Надо исправить:**

Активация валидации должна осуществляться для конкретной формы, на основе которой создается экземпляр класса FormValidator.

Активировать валидацию для всех форм сразу некорректно

2022-08-01 11:13 UTC, antonmishchenkov commented on src/scripts/components/PopupWithForm.js
> +      this.close();
**Надо исправить:**

Закрытие попапа следует осуществлять только после успешного ответа от сервера, следовательно данный вызов необходимо перенести в блок then для соответствующего api запроса внутри функции ```_formData``` в файле index.js

2022-08-01 11:16 UTC, antonmishchenkov commented on src/scripts/index.js
> +Promise.all([api.getProfileInfo(), api.getCards()])
**Отлично:**

Отлично, что используется `Promise.all`

2022-08-01 11:18 UTC, antonmishchenkov commented on src/scripts/index.js
> +    popupWithFormProfile.renderLoading(true);
**Надо исправить:**

Вызов данного метода с аргументом `true` следует осуществлять перед запросом на сервер, то есть перед вызовом `api.patchProfileInfo`.

Следует исправить здесь и везде далее во **всех аналогичных местах**

2022-08-01 11:21 UTC, antonmishchenkov commented on src/scripts/index.js
> +      })
**Надо исправить:**

При сабмите формы добавления карточки также необходимо деактивировать кнопку сабмита, иначе после добавления карточки и последующего повторного открытия формы - кнопка активна - в результате чего есть возможность сделать сабмит с пустыми невалидными полями

2022-08-01 11:21 UTC, antonmishchenkov requested changes
Хорошая работа, так держать! Код аккуратен и читабелен.
Есть ряд замечаний, которые необходимо исправить, чтобы работу можно было принять. Все они отмечены как "Надо исправить".

Успехов на второй итерации!

2022-08-01 18:49 UTC, Gyxer513 commented on src/scripts/index.js
> +    popupWithFormProfile.renderLoading(true);
Исправлено.

2022-08-02 07:31 UTC, Gyxer513 commented on src/scripts/components/card.js
> +      this._buttonLike.classList.remove("photo-grid__heart_black");
Добавлен публичный метод handleLikeCard, который устанавливает лайк и меняет их количество.

2022-08-02 07:51 UTC, Gyxer513 commented on src/scripts/components/PopupWithForm.js
> +      this.close();
Исправлено.

2022-08-02 08:13 UTC, Gyxer513 commented on src/scripts/index.js
> +      })
Исправлено.

2022-08-02 08:42 UTC, Gyxer513 commented on src/scripts/components/card.js
> +      this._buttonLike.classList.remove("photo-grid__heart_black");
Исправлено.

2022-08-03 11:48 UTC, antonmishchenkov commented on src/scripts/index.js
> +    popupWithFormCard.renderLoading(true);
**Не полностью исправлено замечание:**

Данный вызов также необходимо переместить перед вызовом `api.postCards(data)`

2022-08-03 11:49 UTC, antonmishchenkov approved these changes
Хорошо, замечания были исправлены. Осталось одно, но так как оно простое, то работа принимается. Однако, прежде чем приступить к выполнению следующей проектной работы, данное замечание обязательно необходимо исправить.

Успехов в дальнейших проектах!

2022-08-03 12:00 UTC, Gyxer513 commented on src/scripts/index.js
> +    popupWithFormCard.renderLoading(true);
Исправлено.

2022-10-10 11:28 UTC, merged